export const ROUTES = {
    SPLASH: "Splash",
    WELCOME: "Welcome",
    GENDER: "Gender",
    BODY_INFO: "BodyInfo",
    GOAL: "Goal",
    HOME: "Home",
    ANALYSIS: "Analysis",
    DETAILS: "Details",
    WORKOUT: "Workout",
    EXERCISE_DETAIL: "ExerciseDetail",
    ACTIVE_WORKOUT: "ActiveWorkout",
    PROFILE: "Profile",
    DASHBOARD: "Dashboard",
    LOGOUT: "Logout",
    NOTIFICATIONS: "Notifications",
    WORKOUTCALENDAR: "WorkoutCalendar",
    FORGET: "Forget",
    REGISTER: "Register",
    LOGIN: "Login",
    EXERCISE_DETAILS: "ExerciseDetails",
    SETTINGS: "Settings",
    HELP_SUPPORT: "HelpSupport",
    EDIT_GOALS: "EditGoals",
    GOAL_DETAIL: "GoalDetail"
} as const;