export const WORKOUT_ROUTES = {
  WELCOME: "WorkoutWelcome",
  HUB: "WorkoutHub",
  EXPLORE: "ExploreWorkouts",
  COLLECTIONS: "WorkoutCollections",
  SEARCH: "WorkoutSearch",
  FILTERS: "WorkoutFilters",
  FAVORITES: "FavoriteWorkouts",
  DETAILS: "WorkoutDetails",
  EQUIPMENT: "EquipmentSelection",
  EXERCISE: "ExerciseDetails",
  LIBRARY_EXERCISE: "LibraryExerciseDetails",
  INSTRUCTIONS: "ExerciseInstructions",
  VIDEO: "ExerciseVideo",
  SCHEDULE: "WorkoutSchedule",
  DATE_CLASSES: "DateClasses",
  CLASS_DETAILS: "ClassDetails",
  INSTRUCTORS: "Instructors",
  ACTIVE: "WorkoutSession",
  PAUSE: "PauseWorkout",
  SUMMARY: "WorkoutSummary",
  FEEDBACK: "WorkoutFeedback",
  HISTORY: "WorkoutHistory",
} as const;
